{% set name = "django-crispy-forms" %}
{% set version = "1.14.0" %}
{% set sha256 = "35887b8851a931374dd697207a8f56c57a9c5cb9dbf0b9fa54314da5666cea5b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - django >=2.2

about:
  home: https://github.com/django-crispy-forms/django-crispy-forms
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The best way to have DRY Django forms. The app provides a tag and filter that lets you quickly render forms in a div format while providing an enormous amount of capability to configure and control the rendered HTML.
  description: |
    Build programmatic reusable layouts out of components, having full control of the rendered 
    HTML without writing HTML in templates. All this without breaking the standard way of doing 
    things in Django, so it plays nice with any other form application.
    django-crispy-forms supports Python 2.7/Python 3.2+ and Django 1.8+
    Django-crispy-forms supports several frontend frameworks, such as Twitter Bootstrap (versions 2 and 3), 
    Uni-form and Foundation. You can also easily adapt your custom company's one, creating your own, see 
    the docs for more information. You can easily switch among them using CRISPY_TEMPLATE_PACK setting variable.
  doc_url: https://readthedocs.org/projects/django-crispy-forms/
  dev_url: https://github.com/django-crispy-forms/django-crispy-forms

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - smithdc1
